dist: trusty
language: php

matrix:
  include:
    - php: "7.2"
      env: LARAVEL_VERSION="^6.0"
    - php: "7.3"
      env: LARAVEL_VERSION="^6.0"
    - php: "7.3"
      env: LARAVEL_VERSION="^7.0"
    - php: "7.4"
      env: LARAVEL_VERSION="^7.0"

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer require "illuminate/database:${LARAVEL_VERSION}" "illuminate/support:${LARAVEL_VERSION}" --no-update --no-interaction
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text
